### ISSUE TITLE
Add SOCKS proxy support

### ISSUE THREAD

**Issue by OJ** [OJ/gobuster#134] opened 2019-03-29 06:14 UTC
At the moment we support HTTP/S proxies, but we don't support SOCKS from what I can tell. I have tried making use of the environment variables but this doesn't work.

So we need to bake this in.

**Comment by FireFart** [comment] 2019-03-29 07:10
@OJ  this should already be possible? https://go-review.googlesource.com/c/go/+/35488/

Have you tried `socks5://host:port` as a proxy url?

**Comment by OJ** [comment] 2019-03-29 07:17
Didn't work with my socks4 proxy.

**Comment by FireFart** [comment] 2019-03-29 07:21
Jeah the source code change only adds socks5:// support. So is it worth to implement socks4 support manually?

**Comment by FireFart** [comment] 2019-03-29 07:29
Looks like the main problem here is https://godoc.org/golang.org/x/net/proxy not supporting SOCKS4 at all which sucks :/

**Comment by OJ** [comment] 2019-03-29 08:06
Yeah exactly. Maybe I just need to skip that idea then.

Seems stupid.

**Comment by jjhesk** [comment] 2019-08-24 09:41
sock5 is important

**Comment by leejamison** [comment] 2020-06-20 19:24
Hi guys! Gobuster has done wonders for me so I thought it was time to give back to help you guys if I could!

As I type this, I'm successfully running Gobuster over socks5 with zero problems within my PWK/OSCP labs!

1. I installed/configured Ligolo (HIGHLY recommend) on my Kali (attack machine) machine https://github.com/sysdream/ligolo
2. Dropped the Ligolo binary on a compromised Windows machine (victim machine)
3. Started up listener on the attack machine
4. Ran the connection binary on the victim machine to receive a connection on attack machine
5. Per Ligolo instructions, added **socks5 127.0.0.1 1080** to /etc/proxychains.conf
6. Ran the following Gobuster call: gobuster dir -p socks5://127.0.0.1:1080 -u http://<IP> -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt

and it's running as fast as it would be directly connecting to a server (much faster than wfuzz ;) )

I'll also attempt socks4 as soon as I can in the lab to see if I can replicate the same results!

**Comment by Pernat1y** [comment] 2020-06-27 12:46
'--proxy socks5://host:port' work just fine.
I think https://godoc.org/golang.org/x/net/proxy now supports socks5.

**Comment by Pernat1y** [comment] 2020-06-27 12:52
>     5. Per Ligolo instructions, added **socks5 127.0.0.1 1080** to /etc/proxychains.conf
>     6. Ran the following Gobuster call: **gobuster dir -p socks5://127.0.0.1:1080 -u http:// -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt**
You doing it wrong. You just running 'gobuster' as usual. To get use of proxychains, you should start it something like 'proxychains gobuster <args>'.
Your example works just because gobuster now have built-in socks5 support.

**Comment by leejamison** [comment] 2020-07-03 20:25
Confirmed socks4 does not function as of Gobuster 3.0.1 (told you I'd get around to socks4 testing eventually! )

1. Configure SSH Dynamic Port Forwarding **ssh -N -D 127.0.0.1:8081 user@host**

2. set /etc/proxychains.conf to **socks4 127.0.0.1 8081**

3. Using `gobuster dir -p socks4://127.0.0.1:8081 -u http://<IP> -w <wordlist>` resulted in **Error: error on running gobuster: unable to connect to http://<IP>/: Get "http://<IP>/": EOF**

4. Using `Error: error on running gobuster: unable to connect to http://<IP>/: Get "http://<IP>/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

Hope this helps! It would be great to see this implemented!

**Comment by Pernat1y** [comment] 2020-07-09 18:24
socks5://
Works just fine

**Comment by d2hvYW1p** [comment] 2022-06-26 11:20
Hey, I try to run this command "gobuster dir -p socks5://127.0.0.1:1080 -u http://10.20.115.31/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt" but i get " Error: error on parsing arguments: pattern file "socks5://127.0.0.1:1080" does not exist: stat socks5://127.0.0.1:1080: no such file or directory"

**Comment by firefart** [comment] 2022-06-26 12:14
> Hey, I try to run this command "gobuster dir -p socks5://127.0.0.1:1080 -u http://10.20.115.31/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt" but i get " Error: error on parsing arguments: pattern file "socks5://127.0.0.1:1080" does not exist: stat socks5://127.0.0.1:1080: no such file or directory"

use —proxy

**Comment by cybertuxh4xor** [comment] 2023-03-02 12:20
gobuster -q dir --proxy socks5://127.0.0.1:1080 -u http://127.0.0.1:80 -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt
works for me

**Comment by firefart** [comment] 2023-11-19 16:44
still no socks4 support so closing this

**Closed by firefart** 2023-11-19 16:44 UTC
Labels: enhancement
